### ISSUE TITLE
Scope functions can reset Clock

### ISSUE THREAD

**Issue by jlwilliams03** [ganzziani/Xproto-Watch-Firmware#5]
Starting with a set clock, toggling to scope/meter/freq/awg functions, then exiting back to clock shows a time/date reset to "Sat 3-01 7:30A".

**Comment by ganzziani** [comment]
The time keeping timers, RTC and TCF0, now work independently of the CPU. Entering Scope mode will not influence the time. There was another issue with the hardware itself: activating the analog circuit caused a drop in the supply voltage, causing a reset. This was fixed on the latest hardware revision. I will experiment on the previous hardware to see if it can be solved there as well, maybe doing a PWM to slowly turn on the analog circuit.
