### ISSUE TITLE
Resetting Clock: Set day active but not blinking

### ISSUE THREAD

**Issue by jlwilliams03** [ganzziani/Xproto-Watch-Firmware#6]
When setting the clock the element being set blinks to indicate it is active.  You can push buttons to move from element to element  The date will automatically set the day of week.  But an additional button push logically moves to setting the day of week independent of the date.  But the day  of week does not blink-- you are still in set model.

The day of week should blink to indicate set mode is still active.

**Comment by ganzziani** [comment]
I've made some changes. The last element to modify is the year, and now it is shown on the display.
