### ISSUE TITLE
Back-light button delays timekeeping by a half second per press

### ISSUE THREAD

**Issue by kaben** [ganzziani/Xproto-Watch-Firmware#7]
How to reproduce:
- Set oscilloscope-watch time normally within one second to a reference clock.
- Ten times: press back-light button (left top tactile switch `KL`); back light illuminates for one second; wait until back light extinguishes before pressing button again.
- Compare oscilloscope-watch time to reference; typically, oscilloscope watch is now slow by five seconds.

Possible explanation: as of commit 9c94708a23c96617f52d2369d2802621e6f06b0d, back-light button presses are handled in medium-level interrupt handler `PORTF_INT0_vect` defined in `Source / main.c` at line 435. At line 437, `_delay_ms(1000);` is called in medium-priority interrupt context, pausing execution for one second; this causes the timekeeper to skip one period, since the timekeeper runs in a lower-priority interrupt handler, usually twice per second.

Possible solution: instead of a one-second delay in interrupt context, the back light could be illuminated and a "back-light countdown" could be triggered after which the back light could be extinguished. It looks like there may be two unused timers (`TCE1L`, `TCE1H`), one of which could be used for this purpose. Alternatively, this countdown could be handled in an existing timing mechanism (e.g. the timekeeper's `RTC_OVF_vect` interrupt handler defined in `Source / time.c` at line 98).

**Comment by ganzziani** [comment]
Fixed. The time keeping now uses hardware timer TCF0, and it is fed from the RTC clock.

**Comment by kamotswolf** [comment]
This is still somewhat of an issue with the latest firmware. It looks like using the back-light while the time is displays still causes the display to pause. I think I may have an easy solution for this that is based on kaben's suggestion. I'll try to get it tested tonight and let you know how it goes.

**Comment by ganzziani** [comment]
There is a variable that gets out of sync when the backlight button is pressed, but the internal time is actually still ok, it will be synced on the next minute. I'll add something so that this variable gets in sync after pressing the backlight, or perhaps make the backlight run on a PWM so that it doesn't pause the CPU.
